# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom  docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  branches:
    master: # master
      - step:
          name: Deploy to production
          deployment: production
          script: # master deployment
            - ssh -tt root@$PROD_HOST 'sudo su -lc "cd '$APP_PATH' && git fetch origin && git reset --hard origin/master" $PROD_USER && cd '$APP_PATH' && docker-compose up --build -d && docker-cleanup && docker exec -it '$PROD_DOCKER_CONTAINER' sh -c "/venv/bin/python manage.py migrate --noinput && /venv/bin/python manage.py collectstatic --noinput"'
